### ISSUE TITLE
cancellation doesn't seem to work as expected

### ISSUE THREAD

**Issue by rogpeppe** [sdboyer/constext#1]
This program deadlocks forever, even though one of the Cons'd parent contexts has been cancelled.

	package main
	
	import (
		"context"
	
		"github.com/sdboyer/constext"
	)
	
	func main() {
		ctx1, cancel1 := context.WithCancel(context.Background())
		ctx, ctxCancel := constext.Cons(context.Background(), ctx1)
		defer ctxCancel()
		cancel1()
		<-ctx.Done()
	}

**Comment by sdboyer** [comment]
Mm yeah, I think this is a nil channel problem...

**Comment by sdboyer** [comment]
Wait no, it was a dumb typo: ec4a18c 😄
